"""writeoff

Revision ID: 1045ba78a5a3
Revises: 3f777aabecac
Create Date: 2025-06-11 22:15:26.139097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1045ba78a5a3'
down_revision: Union[str, None] = '3f777aabecac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writeofftransfer', 'report_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writeofftransfer', sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
