"""report on goods

Revision ID: 29cc1cba8814
Revises: 0a16d49fa6a6
Create Date: 2025-06-11 22:56:03.382607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29cc1cba8814'
down_revision: Union[str, None] = '0a16d49fa6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reportongoods', sa.Column('shift_type', sa.String(length=20), nullable=False, server_default=''))
    op.add_column('reportongoods', sa.Column('cashier_name', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reportongoods', 'cashier_name')
    op.drop_column('reportongoods', 'shift_type')
    # ### end Alembic commands ###
