"""app 2 column writeoff

Revision ID: 3f777aabecac
Revises: 80b82db785fe
Create Date: 2025-06-11 21:42:49.026330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f777aabecac'
down_revision: Union[str, None] = '80b82db785fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writeofftransfer', sa.Column('shift_type', sa.String(length=20), nullable=False, server_default=''))
    op.add_column('writeofftransfer', sa.Column('cashier_name', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writeofftransfer', 'cashier_name')
    op.drop_column('writeofftransfer', 'shift_type')
    # ### end Alembic commands ###
