"""add table report on goods

Revision ID: 681e2191fa90
Revises: acc052dc1c83
Create Date: 2025-05-28 22:28:26.521416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681e2191fa90'
down_revision: Union[str, None] = 'acc052dc1c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportongoods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kuxnya', sa.JSON(), nullable=False),
    sa.Column('bar', sa.JSON(), nullable=False),
    sa.Column('upakovki_xoz', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportongoods_id'), 'reportongoods', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportongoods_id'), table_name='reportongoods')
    op.drop_table('reportongoods')
    # ### end Alembic commands ###
