"""add inventory management tables

Revision ID: 7b8672c59c23
Revises: 29cc1cba8814
Create Date: 2025-06-12 00:55:01.910024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8672c59c23'
down_revision: Union[str, None] = '29cc1cba8814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyinventoryv2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('shift_type', sa.String(length=20), nullable=False),
    sa.Column('cashier_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inventory_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailyinventoryv2_id'), 'dailyinventoryv2', ['id'], unique=False)
    # Дополнительные индексы для производительности
    op.create_index('ix_dailyinventoryv2_location', 'dailyinventoryv2', ['location'], unique=False)
    op.create_index('ix_dailyinventoryv2_date', 'dailyinventoryv2', ['date'], unique=False)

    op.create_table('inventoryitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_inventoryitem_id'), 'inventoryitem', ['id'], unique=False)
    # Дополнительные индексы для производительности
    op.create_index('ix_inventoryitem_category', 'inventoryitem', ['category'], unique=False)
    op.create_index('ix_inventoryitem_is_active', 'inventoryitem', ['is_active'], unique=False)

    # ### end Alembic commands ###

    # Добавляем начальные товары из существующей системы
    op.execute("""
        INSERT INTO inventoryitem (name, category, unit, description, is_active, sort_order, created_at, updated_at) VALUES
        ('IL Primo (стекло)', 'напитки', 'шт', 'IL Primo в стеклянной бутылке', true, 10, now(), now()),
        ('Вода горная', 'напитки', 'шт', 'Горная вода', true, 20, now(), now()),
        ('Добрый сок ПЭТ', 'напитки', 'шт', 'Сок Добрый в ПЭТ бутылке', true, 30, now(), now()),
        ('Кураговый компот', 'напитки', 'шт', 'Компот из кураги', true, 40, now(), now()),
        ('Напитки ЖБ', 'напитки', 'шт', 'Напитки в жестяных банках', true, 50, now(), now()),
        ('Энергетики', 'напитки', 'шт', 'Энергетические напитки', true, 60, now(), now()),
        ('Колд брю', 'напитки', 'шт', 'Холодный кофе', true, 70, now(), now()),
        ('Кинза напитки', 'напитки', 'шт', 'Напитки бренда Кинза', true, 80, now(), now()),
        ('Палли', 'еда', 'шт', 'Лепешки палли', true, 100, now(), now()),
        ('Барбекю дип', 'еда', 'шт', 'Соус барбекю', true, 110, now(), now()),
        ('Булка на шаурму', 'еда', 'шт', 'Булки для шаурмы', true, 120, now(), now()),
        ('Лаваш', 'еда', 'шт', 'Тонкий лаваш', true, 130, now(), now()),
        ('Лепешки', 'еда', 'шт', 'Различные лепешки', true, 140, now(), now()),
        ('Кетчуп дип', 'еда', 'шт', 'Соус кетчуп', true, 150, now(), now()),
        ('Сырный соус дип', 'еда', 'шт', 'Сырный соус', true, 160, now(), now()),
        ('Курица жареная', 'еда', 'кг', 'Готовая жареная курица', true, 170, now(), now()),
        ('Курица сырая', 'еда', 'кг', 'Сырая курица для приготовления', true, 180, now(), now())
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем дополнительные индексы
    op.drop_index('ix_inventoryitem_is_active', table_name='inventoryitem')
    op.drop_index('ix_inventoryitem_category', table_name='inventoryitem')
    op.drop_index(op.f('ix_inventoryitem_id'), table_name='inventoryitem')
    op.drop_table('inventoryitem')

    op.drop_index('ix_dailyinventoryv2_date', table_name='dailyinventoryv2')
    op.drop_index('ix_dailyinventoryv2_location', table_name='dailyinventoryv2')
    op.drop_index(op.f('ix_dailyinventoryv2_id'), table_name='dailyinventoryv2')
    op.drop_table('dailyinventoryv2')
    # ### end Alembic commands ###