"""add optional date time to writeoff transfer

Revision ID: 91a37f3e1550
Revises: 9cbd7295f535
Create Date: 2025-06-20 19:38:47.816301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a37f3e1550'
down_revision: Union[str, None] = '9cbd7295f535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writeofftransfer', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writeofftransfer', 'date')
    # ### end Alembic commands ###
