"""v rotik

Revision ID: 9cbd7295f535
Revises: 7b8672c59c23
Create Date: 2025-06-12 17:19:41.260937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbd7295f535'
down_revision: Union[str, None] = '7b8672c59c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dailyinventoryv2_date'), table_name='dailyinventoryv2')
    op.drop_index(op.f('ix_dailyinventoryv2_location'), table_name='dailyinventoryv2')
    op.drop_index(op.f('ix_inventoryitem_category'), table_name='inventoryitem')
    op.drop_index(op.f('ix_inventoryitem_is_active'), table_name='inventoryitem')
    op.drop_column('inventoryitem', 'category')
    op.drop_column('inventoryitem', 'sort_order')
    op.drop_column('inventoryitem', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventoryitem', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inventoryitem', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventoryitem', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_inventoryitem_is_active'), 'inventoryitem', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventoryitem_category'), 'inventoryitem', ['category'], unique=False)
    op.create_index(op.f('ix_dailyinventoryv2_location'), 'dailyinventoryv2', ['location'], unique=False)
    op.create_index(op.f('ix_dailyinventoryv2_date'), 'dailyinventoryv2', ['date'], unique=False)
    # ### end Alembic commands ###
