"""add table daily_inventory

Revision ID: acc052dc1c83
Revises: 89e0cb209a17
Create Date: 2025-05-28 09:28:56.762201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc052dc1c83'
down_revision: Union[str, None] = '89e0cb209a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyinventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('shift_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cashier_name', sa.String(length=255), nullable=False),
    sa.Column('il_primo_steklo', sa.SmallInteger(), nullable=False),
    sa.Column('voda_gornaya', sa.SmallInteger(), nullable=False),
    sa.Column('dobri_sok_pet', sa.SmallInteger(), nullable=False),
    sa.Column('kuragovi_kompot', sa.SmallInteger(), nullable=False),
    sa.Column('napitki_jb', sa.SmallInteger(), nullable=False),
    sa.Column('energetiky', sa.SmallInteger(), nullable=False),
    sa.Column('kold_bru', sa.SmallInteger(), nullable=False),
    sa.Column('kinza_napitky', sa.SmallInteger(), nullable=False),
    sa.Column('palli', sa.SmallInteger(), nullable=False),
    sa.Column('barbeku_dip', sa.SmallInteger(), nullable=False),
    sa.Column('bulka_na_shaurmu', sa.SmallInteger(), nullable=False),
    sa.Column('lavash', sa.SmallInteger(), nullable=False),
    sa.Column('ketchup_dip', sa.SmallInteger(), nullable=False),
    sa.Column('sirny_sous_dip', sa.SmallInteger(), nullable=False),
    sa.Column('kuriza_jareny', sa.SmallInteger(), nullable=False),
    sa.Column('kuriza_siraya', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailyinventory_id'), 'dailyinventory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dailyinventory_id'), table_name='dailyinventory')
    op.drop_table('dailyinventory')
    # ### end Alembic commands ###
