"""update

Revision ID: c8bc25711f24
Revises: 85e3e1c3398c
Create Date: 2025-06-04 19:25:04.619357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bc25711f24'
down_revision: Union[str, None] = '85e3e1c3398c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailyinventory', sa.Column('lepeshki', sa.SmallInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailyinventory', 'lepeshki')
    # ### end Alembic commands ###
