"""update  model shift report

Revision ID: d9d00d6f2ec7
Revises: ded0503ef02b
Create Date: 2025-05-26 17:52:24.971725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d00d6f2ec7'
down_revision: Union[str, None] = 'ded0503ef02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_reports', sa.Column('location', sa.String(length=255), nullable=False))
    op.drop_column('shift_reports', 'location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_reports', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('shift_reports', 'location')
    # ### end Alembic commands ###
