"""add writeoff_transfer table

Revision ID: f347aa0dfda3
Revises: 681e2191fa90
Create Date: 2025-05-29 17:28:29.830170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f347aa0dfda3'
down_revision: Union[str, None] = '681e2191fa90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writeofftransfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('writeoffs', sa.JSON(), nullable=False),
    sa.Column('transfers', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writeofftransfer_id'), 'writeofftransfer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writeofftransfer_id'), table_name='writeofftransfer')
    op.drop_table('writeofftransfer')
    # ### end Alembic commands ###
